package com.github.adalrsjr1.specpatterns

enum ExpressionPattern {
	ABSENCE, 
	EXISTENCE,
	BOUNDED_EXISTENCE,
	UNIVERSALITY,
	PRECEDENCE,
	RESPONSE,
	PRECEDENCE_CHAIN_ONE,
	PRECEDENCE_CHAIN_TWO,
	RESPONSE_CHAIN_ONE,
	RESPONSE_CHAIN_TWO,
	CONSTRAINED_CHAIN
}
